// Auto generated MAVLink parsing script

mavlink_msgs = []
mavlink_msgs[150] = { name: "SENSOR_OFFSETS", CRC: 134 }
mavlink_msgs[151] = { name: "SET_MAG_OFFSETS", CRC: 219 }
mavlink_msgs[152] = { name: "MEMINFO", CRC: 208 }
mavlink_msgs[153] = { name: "AP_ADC", CRC: 188 }
mavlink_msgs[154] = { name: "DIGICAM_CONFIGURE", CRC: 84 }
mavlink_msgs[155] = { name: "DIGICAM_CONTROL", CRC: 22 }
mavlink_msgs[156] = { name: "MOUNT_CONFIGURE", CRC: 19 }
mavlink_msgs[157] = { name: "MOUNT_CONTROL", CRC: 21 }
mavlink_msgs[158] = { name: "MOUNT_STATUS", CRC: 134 }
mavlink_msgs[160] = { name: "FENCE_POINT", CRC: 78 }
mavlink_msgs[161] = { name: "FENCE_FETCH_POINT", CRC: 68 }
mavlink_msgs[163] = { name: "AHRS", CRC: 127 }
mavlink_msgs[164] = { name: "SIMSTATE", CRC: 154 }
mavlink_msgs[165] = { name: "HWSTATUS", CRC: 21 }
mavlink_msgs[166] = { name: "RADIO", CRC: 21 }
mavlink_msgs[167] = { name: "LIMITS_STATUS", CRC: 144 }
mavlink_msgs[168] = { name: "WIND", CRC: 1 }
mavlink_msgs[169] = { name: "DATA16", CRC: 234 }
mavlink_msgs[170] = { name: "DATA32", CRC: 73 }
mavlink_msgs[171] = { name: "DATA64", CRC: 181 }
mavlink_msgs[172] = { name: "DATA96", CRC: 22 }
mavlink_msgs[173] = { name: "RANGEFINDER", CRC: 83 }
mavlink_msgs[174] = { name: "AIRSPEED_AUTOCAL", CRC: 167 }
mavlink_msgs[175] = { name: "RALLY_POINT", CRC: 138 }
mavlink_msgs[176] = { name: "RALLY_FETCH_POINT", CRC: 234 }
mavlink_msgs[177] = { name: "COMPASSMOT_STATUS", CRC: 240 }
mavlink_msgs[178] = { name: "AHRS2", CRC: 47 }
mavlink_msgs[179] = { name: "CAMERA_STATUS", CRC: 189 }
mavlink_msgs[180] = { name: "CAMERA_FEEDBACK", CRC: 52 }
mavlink_msgs[181] = { name: "BATTERY2", CRC: 174 }
mavlink_msgs[182] = { name: "AHRS3", CRC: 229 }
mavlink_msgs[183] = { name: "AUTOPILOT_VERSION_REQUEST", CRC: 85 }
mavlink_msgs[184] = { name: "REMOTE_LOG_DATA_BLOCK", CRC: 159 }
mavlink_msgs[185] = { name: "REMOTE_LOG_BLOCK_STATUS", CRC: 186 }
mavlink_msgs[186] = { name: "LED_CONTROL", CRC: 72 }
mavlink_msgs[191] = { name: "MAG_CAL_PROGRESS", CRC: 92 }
mavlink_msgs[193] = { name: "EKF_STATUS_REPORT", CRC: 71 }
mavlink_msgs[194] = { name: "PID_TUNING", CRC: 98 }
mavlink_msgs[195] = { name: "DEEPSTALL", CRC: 120 }
mavlink_msgs[200] = { name: "GIMBAL_REPORT", CRC: 134 }
mavlink_msgs[201] = { name: "GIMBAL_CONTROL", CRC: 205 }
mavlink_msgs[214] = { name: "GIMBAL_TORQUE_CMD_REPORT", CRC: 69 }
mavlink_msgs[215] = { name: "GOPRO_HEARTBEAT", CRC: 101 }
mavlink_msgs[216] = { name: "GOPRO_GET_REQUEST", CRC: 50 }
mavlink_msgs[217] = { name: "GOPRO_GET_RESPONSE", CRC: 202 }
mavlink_msgs[218] = { name: "GOPRO_SET_REQUEST", CRC: 17 }
mavlink_msgs[219] = { name: "GOPRO_SET_RESPONSE", CRC: 162 }
mavlink_msgs[226] = { name: "RPM", CRC: 207 }
mavlink_msgs[11000] = { name: "DEVICE_OP_READ", CRC: 134 }
mavlink_msgs[11001] = { name: "DEVICE_OP_READ_REPLY", CRC: 15 }
mavlink_msgs[11002] = { name: "DEVICE_OP_WRITE", CRC: 234 }
mavlink_msgs[11003] = { name: "DEVICE_OP_WRITE_REPLY", CRC: 64 }
mavlink_msgs[11004] = { name: "SECURE_COMMAND", CRC: 11 }
mavlink_msgs[11005] = { name: "SECURE_COMMAND_REPLY", CRC: 93 }
mavlink_msgs[11010] = { name: "ADAP_TUNING", CRC: 46 }
mavlink_msgs[11011] = { name: "VISION_POSITION_DELTA", CRC: 106 }
mavlink_msgs[11020] = { name: "AOA_SSA", CRC: 205 }
mavlink_msgs[11030] = { name: "ESC_TELEMETRY_1_TO_4", CRC: 144 }
mavlink_msgs[11031] = { name: "ESC_TELEMETRY_5_TO_8", CRC: 133 }
mavlink_msgs[11032] = { name: "ESC_TELEMETRY_9_TO_12", CRC: 85 }
mavlink_msgs[11033] = { name: "OSD_PARAM_CONFIG", CRC: 195 }
mavlink_msgs[11034] = { name: "OSD_PARAM_CONFIG_REPLY", CRC: 79 }
mavlink_msgs[11035] = { name: "OSD_PARAM_SHOW_CONFIG", CRC: 128 }
mavlink_msgs[11036] = { name: "OSD_PARAM_SHOW_CONFIG_REPLY", CRC: 177 }
mavlink_msgs[11037] = { name: "OBSTACLE_DISTANCE_3D", CRC: 130 }
mavlink_msgs[11038] = { name: "WATER_DEPTH", CRC: 47 }
mavlink_msgs[11039] = { name: "MCU_STATUS", CRC: 142 }
mavlink_msgs[11040] = { name: "ESC_TELEMETRY_13_TO_16", CRC: 132 }
mavlink_msgs[11041] = { name: "ESC_TELEMETRY_17_TO_20", CRC: 208 }
mavlink_msgs[11042] = { name: "ESC_TELEMETRY_21_TO_24", CRC: 201 }
mavlink_msgs[11043] = { name: "ESC_TELEMETRY_25_TO_28", CRC: 193 }
mavlink_msgs[11044] = { name: "ESC_TELEMETRY_29_TO_32", CRC: 189 }
mavlink_msgs[223] = { name: "COMMAND_INT_STAMPED", CRC: 119 }
mavlink_msgs[224] = { name: "COMMAND_LONG_STAMPED", CRC: 102 }
mavlink_msgs[8002] = { name: "SENS_POWER", CRC: 218 }
mavlink_msgs[8003] = { name: "SENS_MPPT", CRC: 231 }
mavlink_msgs[8004] = { name: "ASLCTRL_DATA", CRC: 172 }
mavlink_msgs[8005] = { name: "ASLCTRL_DEBUG", CRC: 251 }
mavlink_msgs[8006] = { name: "ASLUAV_STATUS", CRC: 97 }
mavlink_msgs[8007] = { name: "EKF_EXT", CRC: 64 }
mavlink_msgs[8008] = { name: "ASL_OBCTRL", CRC: 234 }
mavlink_msgs[8009] = { name: "SENS_ATMOS", CRC: 144 }
mavlink_msgs[8010] = { name: "SENS_BATMON", CRC: 155 }
mavlink_msgs[8011] = { name: "FW_SOARING_DATA", CRC: 20 }
mavlink_msgs[8012] = { name: "SENSORPOD_STATUS", CRC: 54 }
mavlink_msgs[8013] = { name: "SENS_POWER_BOARD", CRC: 222 }
mavlink_msgs[8014] = { name: "GSM_LINK_STATUS", CRC: 200 }
mavlink_msgs[8015] = { name: "SATCOM_LINK_STATUS", CRC: 23 }
mavlink_msgs[8016] = { name: "SENSOR_AIRFLOW_ANGLES", CRC: 149 }
mavlink_msgs[1] = { name: "SYS_STATUS", CRC: 124 }
mavlink_msgs[2] = { name: "SYSTEM_TIME", CRC: 137 }
mavlink_msgs[4] = { name: "PING", CRC: 237 }
mavlink_msgs[5] = { name: "CHANGE_OPERATOR_CONTROL", CRC: 217 }
mavlink_msgs[6] = { name: "CHANGE_OPERATOR_CONTROL_ACK", CRC: 104 }
mavlink_msgs[7] = { name: "AUTH_KEY", CRC: 119 }
mavlink_msgs[11] = { name: "SET_MODE", CRC: 89 }
mavlink_msgs[20] = { name: "PARAM_REQUEST_READ", CRC: 214 }
mavlink_msgs[21] = { name: "PARAM_REQUEST_LIST", CRC: 159 }
mavlink_msgs[22] = { name: "PARAM_VALUE", CRC: 220 }
mavlink_msgs[23] = { name: "PARAM_SET", CRC: 168 }
mavlink_msgs[24] = { name: "GPS_RAW_INT", CRC: 24 }
mavlink_msgs[25] = { name: "GPS_STATUS", CRC: 23 }
mavlink_msgs[26] = { name: "SCALED_IMU", CRC: 170 }
mavlink_msgs[27] = { name: "RAW_IMU", CRC: 144 }
mavlink_msgs[28] = { name: "RAW_PRESSURE", CRC: 67 }
mavlink_msgs[29] = { name: "SCALED_PRESSURE", CRC: 115 }
mavlink_msgs[30] = { name: "ATTITUDE", CRC: 39 }
mavlink_msgs[31] = { name: "ATTITUDE_QUATERNION", CRC: 246 }
mavlink_msgs[32] = { name: "LOCAL_POSITION_NED", CRC: 185 }
mavlink_msgs[33] = { name: "GLOBAL_POSITION_INT", CRC: 104 }
mavlink_msgs[34] = { name: "RC_CHANNELS_SCALED", CRC: 237 }
mavlink_msgs[35] = { name: "RC_CHANNELS_RAW", CRC: 244 }
mavlink_msgs[36] = { name: "SERVO_OUTPUT_RAW", CRC: 222 }
mavlink_msgs[37] = { name: "MISSION_REQUEST_PARTIAL_LIST", CRC: 212 }
mavlink_msgs[38] = { name: "MISSION_WRITE_PARTIAL_LIST", CRC: 9 }
mavlink_msgs[39] = { name: "MISSION_ITEM", CRC: 254 }
mavlink_msgs[40] = { name: "MISSION_REQUEST", CRC: 230 }
mavlink_msgs[41] = { name: "MISSION_SET_CURRENT", CRC: 28 }
mavlink_msgs[42] = { name: "MISSION_CURRENT", CRC: 28 }
mavlink_msgs[43] = { name: "MISSION_REQUEST_LIST", CRC: 132 }
mavlink_msgs[44] = { name: "MISSION_COUNT", CRC: 221 }
mavlink_msgs[45] = { name: "MISSION_CLEAR_ALL", CRC: 232 }
mavlink_msgs[46] = { name: "MISSION_ITEM_REACHED", CRC: 11 }
mavlink_msgs[47] = { name: "MISSION_ACK", CRC: 153 }
mavlink_msgs[48] = { name: "SET_GPS_GLOBAL_ORIGIN", CRC: 41 }
mavlink_msgs[49] = { name: "GPS_GLOBAL_ORIGIN", CRC: 39 }
mavlink_msgs[50] = { name: "PARAM_MAP_RC", CRC: 78 }
mavlink_msgs[51] = { name: "MISSION_REQUEST_INT", CRC: 196 }
mavlink_msgs[54] = { name: "SAFETY_SET_ALLOWED_AREA", CRC: 15 }
mavlink_msgs[55] = { name: "SAFETY_ALLOWED_AREA", CRC: 3 }
mavlink_msgs[61] = { name: "ATTITUDE_QUATERNION_COV", CRC: 167 }
mavlink_msgs[62] = { name: "NAV_CONTROLLER_OUTPUT", CRC: 183 }
mavlink_msgs[63] = { name: "GLOBAL_POSITION_INT_COV", CRC: 119 }
mavlink_msgs[64] = { name: "LOCAL_POSITION_NED_COV", CRC: 191 }
mavlink_msgs[65] = { name: "RC_CHANNELS", CRC: 118 }
mavlink_msgs[66] = { name: "REQUEST_DATA_STREAM", CRC: 148 }
mavlink_msgs[67] = { name: "DATA_STREAM", CRC: 21 }
mavlink_msgs[69] = { name: "MANUAL_CONTROL", CRC: 243 }
mavlink_msgs[70] = { name: "RC_CHANNELS_OVERRIDE", CRC: 124 }
mavlink_msgs[73] = { name: "MISSION_ITEM_INT", CRC: 38 }
mavlink_msgs[74] = { name: "VFR_HUD", CRC: 20 }
mavlink_msgs[75] = { name: "COMMAND_INT", CRC: 158 }
mavlink_msgs[76] = { name: "COMMAND_LONG", CRC: 152 }
mavlink_msgs[77] = { name: "COMMAND_ACK", CRC: 143 }
mavlink_msgs[81] = { name: "MANUAL_SETPOINT", CRC: 106 }
mavlink_msgs[82] = { name: "SET_ATTITUDE_TARGET", CRC: 49 }
mavlink_msgs[83] = { name: "ATTITUDE_TARGET", CRC: 22 }
mavlink_msgs[84] = { name: "SET_POSITION_TARGET_LOCAL_NED", CRC: 143 }
mavlink_msgs[85] = { name: "POSITION_TARGET_LOCAL_NED", CRC: 140 }
mavlink_msgs[86] = { name: "SET_POSITION_TARGET_GLOBAL_INT", CRC: 5 }
mavlink_msgs[87] = { name: "POSITION_TARGET_GLOBAL_INT", CRC: 150 }
mavlink_msgs[89] = { name: "LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET", CRC: 231 }
mavlink_msgs[90] = { name: "HIL_STATE", CRC: 183 }
mavlink_msgs[91] = { name: "HIL_CONTROLS", CRC: 63 }
mavlink_msgs[92] = { name: "HIL_RC_INPUTS_RAW", CRC: 54 }
mavlink_msgs[93] = { name: "HIL_ACTUATOR_CONTROLS", CRC: 47 }
mavlink_msgs[100] = { name: "OPTICAL_FLOW", CRC: 175 }
mavlink_msgs[101] = { name: "GLOBAL_VISION_POSITION_ESTIMATE", CRC: 102 }
mavlink_msgs[102] = { name: "VISION_POSITION_ESTIMATE", CRC: 158 }
mavlink_msgs[103] = { name: "VISION_SPEED_ESTIMATE", CRC: 208 }
mavlink_msgs[104] = { name: "VICON_POSITION_ESTIMATE", CRC: 56 }
mavlink_msgs[105] = { name: "HIGHRES_IMU", CRC: 93 }
mavlink_msgs[106] = { name: "OPTICAL_FLOW_RAD", CRC: 138 }
mavlink_msgs[107] = { name: "HIL_SENSOR", CRC: 108 }
mavlink_msgs[108] = { name: "SIM_STATE", CRC: 32 }
mavlink_msgs[109] = { name: "RADIO_STATUS", CRC: 185 }
mavlink_msgs[110] = { name: "FILE_TRANSFER_PROTOCOL", CRC: 84 }
mavlink_msgs[111] = { name: "TIMESYNC", CRC: 34 }
mavlink_msgs[112] = { name: "CAMERA_TRIGGER", CRC: 174 }
mavlink_msgs[113] = { name: "HIL_GPS", CRC: 124 }
mavlink_msgs[114] = { name: "HIL_OPTICAL_FLOW", CRC: 237 }
mavlink_msgs[115] = { name: "HIL_STATE_QUATERNION", CRC: 4 }
mavlink_msgs[116] = { name: "SCALED_IMU2", CRC: 76 }
mavlink_msgs[117] = { name: "LOG_REQUEST_LIST", CRC: 128 }
mavlink_msgs[118] = { name: "LOG_ENTRY", CRC: 56 }
mavlink_msgs[119] = { name: "LOG_REQUEST_DATA", CRC: 116 }
mavlink_msgs[120] = { name: "LOG_DATA", CRC: 134 }
mavlink_msgs[121] = { name: "LOG_ERASE", CRC: 237 }
mavlink_msgs[122] = { name: "LOG_REQUEST_END", CRC: 203 }
mavlink_msgs[123] = { name: "GPS_INJECT_DATA", CRC: 250 }
mavlink_msgs[124] = { name: "GPS2_RAW", CRC: 87 }
mavlink_msgs[125] = { name: "POWER_STATUS", CRC: 203 }
mavlink_msgs[126] = { name: "SERIAL_CONTROL", CRC: 220 }
mavlink_msgs[127] = { name: "GPS_RTK", CRC: 25 }
mavlink_msgs[128] = { name: "GPS2_RTK", CRC: 226 }
mavlink_msgs[129] = { name: "SCALED_IMU3", CRC: 46 }
mavlink_msgs[130] = { name: "DATA_TRANSMISSION_HANDSHAKE", CRC: 29 }
mavlink_msgs[131] = { name: "ENCAPSULATED_DATA", CRC: 223 }
mavlink_msgs[132] = { name: "DISTANCE_SENSOR", CRC: 85 }
mavlink_msgs[133] = { name: "TERRAIN_REQUEST", CRC: 6 }
mavlink_msgs[134] = { name: "TERRAIN_DATA", CRC: 229 }
mavlink_msgs[135] = { name: "TERRAIN_CHECK", CRC: 203 }
mavlink_msgs[136] = { name: "TERRAIN_REPORT", CRC: 1 }
mavlink_msgs[137] = { name: "SCALED_PRESSURE2", CRC: 195 }
mavlink_msgs[138] = { name: "ATT_POS_MOCAP", CRC: 109 }
mavlink_msgs[139] = { name: "SET_ACTUATOR_CONTROL_TARGET", CRC: 168 }
mavlink_msgs[140] = { name: "ACTUATOR_CONTROL_TARGET", CRC: 181 }
mavlink_msgs[141] = { name: "ALTITUDE", CRC: 47 }
mavlink_msgs[142] = { name: "RESOURCE_REQUEST", CRC: 72 }
mavlink_msgs[143] = { name: "SCALED_PRESSURE3", CRC: 131 }
mavlink_msgs[144] = { name: "FOLLOW_TARGET", CRC: 127 }
mavlink_msgs[146] = { name: "CONTROL_SYSTEM_STATE", CRC: 103 }
mavlink_msgs[147] = { name: "BATTERY_STATUS", CRC: 154 }
mavlink_msgs[148] = { name: "AUTOPILOT_VERSION", CRC: 178 }
mavlink_msgs[149] = { name: "LANDING_TARGET", CRC: 200 }
mavlink_msgs[162] = { name: "FENCE_STATUS", CRC: 189 }
mavlink_msgs[192] = { name: "MAG_CAL_REPORT", CRC: 36 }
mavlink_msgs[225] = { name: "EFI_STATUS", CRC: 208 }
mavlink_msgs[230] = { name: "ESTIMATOR_STATUS", CRC: 163 }
mavlink_msgs[231] = { name: "WIND_COV", CRC: 105 }
mavlink_msgs[232] = { name: "GPS_INPUT", CRC: 151 }
mavlink_msgs[233] = { name: "GPS_RTCM_DATA", CRC: 35 }
mavlink_msgs[234] = { name: "HIGH_LATENCY", CRC: 150 }
mavlink_msgs[235] = { name: "HIGH_LATENCY2", CRC: 179 }
mavlink_msgs[241] = { name: "VIBRATION", CRC: 90 }
mavlink_msgs[242] = { name: "HOME_POSITION", CRC: 104 }
mavlink_msgs[243] = { name: "SET_HOME_POSITION", CRC: 85 }
mavlink_msgs[244] = { name: "MESSAGE_INTERVAL", CRC: 95 }
mavlink_msgs[245] = { name: "EXTENDED_SYS_STATE", CRC: 130 }
mavlink_msgs[246] = { name: "ADSB_VEHICLE", CRC: 184 }
mavlink_msgs[247] = { name: "COLLISION", CRC: 81 }
mavlink_msgs[248] = { name: "V2_EXTENSION", CRC: 8 }
mavlink_msgs[249] = { name: "MEMORY_VECT", CRC: 204 }
mavlink_msgs[250] = { name: "DEBUG_VECT", CRC: 49 }
mavlink_msgs[251] = { name: "NAMED_VALUE_FLOAT", CRC: 170 }
mavlink_msgs[252] = { name: "NAMED_VALUE_INT", CRC: 44 }
mavlink_msgs[253] = { name: "STATUSTEXT", CRC: 83 }
mavlink_msgs[254] = { name: "DEBUG", CRC: 46 }
mavlink_msgs[256] = { name: "SETUP_SIGNING", CRC: 71 }
mavlink_msgs[257] = { name: "BUTTON_CHANGE", CRC: 131 }
mavlink_msgs[258] = { name: "PLAY_TUNE", CRC: 187 }
mavlink_msgs[259] = { name: "CAMERA_INFORMATION", CRC: 92 }
mavlink_msgs[260] = { name: "CAMERA_SETTINGS", CRC: 146 }
mavlink_msgs[261] = { name: "STORAGE_INFORMATION", CRC: 179 }
mavlink_msgs[262] = { name: "CAMERA_CAPTURE_STATUS", CRC: 12 }
mavlink_msgs[263] = { name: "CAMERA_IMAGE_CAPTURED", CRC: 133 }
mavlink_msgs[264] = { name: "FLIGHT_INFORMATION", CRC: 49 }
mavlink_msgs[265] = { name: "MOUNT_ORIENTATION", CRC: 26 }
mavlink_msgs[266] = { name: "LOGGING_DATA", CRC: 193 }
mavlink_msgs[267] = { name: "LOGGING_DATA_ACKED", CRC: 35 }
mavlink_msgs[268] = { name: "LOGGING_ACK", CRC: 14 }
mavlink_msgs[269] = { name: "VIDEO_STREAM_INFORMATION", CRC: 109 }
mavlink_msgs[270] = { name: "VIDEO_STREAM_STATUS", CRC: 59 }
mavlink_msgs[271] = { name: "CAMERA_FOV_STATUS", CRC: 22 }
mavlink_msgs[275] = { name: "CAMERA_TRACKING_IMAGE_STATUS", CRC: 126 }
mavlink_msgs[276] = { name: "CAMERA_TRACKING_GEO_STATUS", CRC: 18 }
mavlink_msgs[280] = { name: "GIMBAL_MANAGER_INFORMATION", CRC: 70 }
mavlink_msgs[281] = { name: "GIMBAL_MANAGER_STATUS", CRC: 48 }
mavlink_msgs[282] = { name: "GIMBAL_MANAGER_SET_ATTITUDE", CRC: 123 }
mavlink_msgs[283] = { name: "GIMBAL_DEVICE_INFORMATION", CRC: 74 }
mavlink_msgs[284] = { name: "GIMBAL_DEVICE_SET_ATTITUDE", CRC: 99 }
mavlink_msgs[285] = { name: "GIMBAL_DEVICE_ATTITUDE_STATUS", CRC: 137 }
mavlink_msgs[286] = { name: "AUTOPILOT_STATE_FOR_GIMBAL_DEVICE", CRC: 210 }
mavlink_msgs[287] = { name: "GIMBAL_MANAGER_SET_PITCHYAW", CRC: 1 }
mavlink_msgs[288] = { name: "GIMBAL_MANAGER_SET_MANUAL_CONTROL", CRC: 20 }
mavlink_msgs[299] = { name: "WIFI_CONFIG_AP", CRC: 19 }
mavlink_msgs[301] = { name: "AIS_VESSEL", CRC: 243 }
mavlink_msgs[310] = { name: "UAVCAN_NODE_STATUS", CRC: 28 }
mavlink_msgs[311] = { name: "UAVCAN_NODE_INFO", CRC: 95 }
mavlink_msgs[320] = { name: "PARAM_EXT_REQUEST_READ", CRC: 243 }
mavlink_msgs[321] = { name: "PARAM_EXT_REQUEST_LIST", CRC: 88 }
mavlink_msgs[322] = { name: "PARAM_EXT_VALUE", CRC: 243 }
mavlink_msgs[323] = { name: "PARAM_EXT_SET", CRC: 78 }
mavlink_msgs[324] = { name: "PARAM_EXT_ACK", CRC: 132 }
mavlink_msgs[330] = { name: "OBSTACLE_DISTANCE", CRC: 23 }
mavlink_msgs[331] = { name: "ODOMETRY", CRC: 91 }
mavlink_msgs[335] = { name: "ISBD_LINK_STATUS", CRC: 225 }
mavlink_msgs[339] = { name: "RAW_RPM", CRC: 199 }
mavlink_msgs[340] = { name: "UTM_GLOBAL_POSITION", CRC: 99 }
mavlink_msgs[350] = { name: "DEBUG_FLOAT_ARRAY", CRC: 232 }
mavlink_msgs[370] = { name: "SMART_BATTERY_INFO", CRC: 75 }
mavlink_msgs[373] = { name: "GENERATOR_STATUS", CRC: 117 }
mavlink_msgs[375] = { name: "ACTUATOR_OUTPUT_STATUS", CRC: 251 }
mavlink_msgs[376] = { name: "RELAY_STATUS", CRC: 199 }
mavlink_msgs[385] = { name: "TUNNEL", CRC: 147 }
mavlink_msgs[386] = { name: "CAN_FRAME", CRC: 132 }
mavlink_msgs[387] = { name: "CANFD_FRAME", CRC: 4 }
mavlink_msgs[388] = { name: "CAN_FILTER_MODIFY", CRC: 8 }
mavlink_msgs[9000] = { name: "WHEEL_DISTANCE", CRC: 113 }
mavlink_msgs[9005] = { name: "WINCH_STATUS", CRC: 117 }
mavlink_msgs[12900] = { name: "OPEN_DRONE_ID_BASIC_ID", CRC: 114 }
mavlink_msgs[12901] = { name: "OPEN_DRONE_ID_LOCATION", CRC: 254 }
mavlink_msgs[12902] = { name: "OPEN_DRONE_ID_AUTHENTICATION", CRC: 140 }
mavlink_msgs[12903] = { name: "OPEN_DRONE_ID_SELF_ID", CRC: 249 }
mavlink_msgs[12904] = { name: "OPEN_DRONE_ID_SYSTEM", CRC: 77 }
mavlink_msgs[12905] = { name: "OPEN_DRONE_ID_OPERATOR_ID", CRC: 49 }
mavlink_msgs[12918] = { name: "OPEN_DRONE_ID_ARM_STATUS", CRC: 139 }
mavlink_msgs[12915] = { name: "OPEN_DRONE_ID_MESSAGE_PACK", CRC: 94 }
mavlink_msgs[12919] = { name: "OPEN_DRONE_ID_SYSTEM_UPDATE", CRC: 7 }
mavlink_msgs[12920] = { name: "HYGROMETER_SENSOR", CRC: 20 }
mavlink_msgs[53] = { name: "MISSION_CHECKSUM", CRC: 3 }
mavlink_msgs[295] = { name: "AIRSPEED", CRC: 234 }
mavlink_msgs[42000] = { name: "ICAROUS_HEARTBEAT", CRC: 227 }
mavlink_msgs[42001] = { name: "ICAROUS_KINEMATIC_BANDS", CRC: 239 }
mavlink_msgs[0] = { name: "HEARTBEAT", CRC: 50 }
mavlink_msgs[17150] = { name: "ARRAY_TEST_0", CRC: 26 }
mavlink_msgs[17151] = { name: "ARRAY_TEST_1", CRC: 72 }
mavlink_msgs[17153] = { name: "ARRAY_TEST_3", CRC: 19 }
mavlink_msgs[17154] = { name: "ARRAY_TEST_4", CRC: 89 }
mavlink_msgs[17155] = { name: "ARRAY_TEST_5", CRC: 27 }
mavlink_msgs[17156] = { name: "ARRAY_TEST_6", CRC: 14 }
mavlink_msgs[17157] = { name: "ARRAY_TEST_7", CRC: 187 }
mavlink_msgs[17158] = { name: "ARRAY_TEST_8", CRC: 106 }
mavlink_msgs[17000] = { name: "TEST_TYPES", CRC: 103 }
mavlink_msgs[220] = { name: "NAV_FILTER_BIAS", CRC: 34 }
mavlink_msgs[221] = { name: "RADIO_CALIBRATION", CRC: 71 }
mavlink_msgs[222] = { name: "UALBERTA_SYS_STATUS", CRC: 15 }
mavlink_msgs[10001] = { name: "UAVIONIX_ADSB_OUT_CFG", CRC: 209 }
mavlink_msgs[10002] = { name: "UAVIONIX_ADSB_OUT_DYNAMIC", CRC: 186 }
mavlink_msgs[10003] = { name: "UAVIONIX_ADSB_TRANSCEIVER_HEALTH_REPORT", CRC: 4 }
mavlink_msgs[10004] = { name: "UAVIONIX_ADSB_OUT_CFG_REGISTRATION", CRC: 133 }
mavlink_msgs[10005] = { name: "UAVIONIX_ADSB_OUT_CFG_FLIGHTID", CRC: 103 }
mavlink_msgs[10006] = { name: "UAVIONIX_ADSB_GET", CRC: 193 }
mavlink_msgs[10007] = { name: "UAVIONIX_ADSB_OUT_CONTROL", CRC: 71 }
mavlink_msgs[10008] = { name: "UAVIONIX_ADSB_OUT_STATUS", CRC: 240 }
mavlink_msgs[10151] = { name: "LOWEHEISER_GOV_EFI", CRC: 195 }
mavlink_msgs[60001] = { name: "STORM32_GIMBAL_DEVICE_STATUS", CRC: 186 }
mavlink_msgs[60002] = { name: "STORM32_GIMBAL_DEVICE_CONTROL", CRC: 69 }
mavlink_msgs[60010] = { name: "STORM32_GIMBAL_MANAGER_INFORMATION", CRC: 208 }
mavlink_msgs[60011] = { name: "STORM32_GIMBAL_MANAGER_STATUS", CRC: 183 }
mavlink_msgs[60012] = { name: "STORM32_GIMBAL_MANAGER_CONTROL", CRC: 99 }
mavlink_msgs[60013] = { name: "STORM32_GIMBAL_MANAGER_CONTROL_PITCHYAW", CRC: 129 }
mavlink_msgs[60014] = { name: "STORM32_GIMBAL_MANAGER_CORRECT_ROLL", CRC: 134 }
mavlink_msgs[60015] = { name: "STORM32_GIMBAL_MANAGER_PROFILE", CRC: 78 }
mavlink_msgs[60020] = { name: "QSHOT_STATUS", CRC: 202 }
mavlink_msgs[60025] = { name: "COMPONENT_PREARM_STATUS", CRC: 20 }
mavlink_msgs[60050] = { name: "AVSS_PRS_SYS_STATUS", CRC: 220 }
mavlink_msgs[60051] = { name: "AVSS_DRONE_POSITION", CRC: 245 }
mavlink_msgs[60052] = { name: "AVSS_DRONE_IMU", CRC: 101 }
mavlink_msgs[60053] = { name: "AVSS_DRONE_OPERATION_MODE", CRC: 45 }
mavlink_msgs[50001] = { name: "CUBEPILOT_RAW_RC", CRC: 246 }
mavlink_msgs[50002] = { name: "HERELINK_VIDEO_STREAM_INFORMATION", CRC: 181 }
mavlink_msgs[50003] = { name: "HERELINK_TELEM", CRC: 62 }
mavlink_msgs[50004] = { name: "CUBEPILOT_FIRMWARE_UPDATE_START", CRC: 240 }
mavlink_msgs[50005] = { name: "CUBEPILOT_FIRMWARE_UPDATE_RESP", CRC: 152 }
mavlink_msgs[52000] = { name: "AIRLINK_AUTH", CRC: 13 }
mavlink_msgs[52001] = { name: "AIRLINK_AUTH_RESPONSE", CRC: 239 }

MAV_COMPONENT = []
MAV_COMPONENT[0] = "MAV_COMP_ID_ALL"
MAV_COMPONENT[1] = "MAV_COMP_ID_AUTOPILOT1"
MAV_COMPONENT[25] = "MAV_COMP_ID_USER1"
MAV_COMPONENT[26] = "MAV_COMP_ID_USER2"
MAV_COMPONENT[27] = "MAV_COMP_ID_USER3"
MAV_COMPONENT[28] = "MAV_COMP_ID_USER4"
MAV_COMPONENT[29] = "MAV_COMP_ID_USER5"
MAV_COMPONENT[30] = "MAV_COMP_ID_USER6"
MAV_COMPONENT[31] = "MAV_COMP_ID_USER7"
MAV_COMPONENT[32] = "MAV_COMP_ID_USER8"
MAV_COMPONENT[33] = "MAV_COMP_ID_USER9"
MAV_COMPONENT[34] = "MAV_COMP_ID_USER10"
MAV_COMPONENT[35] = "MAV_COMP_ID_USER11"
MAV_COMPONENT[36] = "MAV_COMP_ID_USER12"
MAV_COMPONENT[37] = "MAV_COMP_ID_USER13"
MAV_COMPONENT[38] = "MAV_COMP_ID_USER14"
MAV_COMPONENT[39] = "MAV_COMP_ID_USER15"
MAV_COMPONENT[40] = "MAV_COMP_ID_USER16"
MAV_COMPONENT[41] = "MAV_COMP_ID_USER17"
MAV_COMPONENT[42] = "MAV_COMP_ID_USER18"
MAV_COMPONENT[43] = "MAV_COMP_ID_USER19"
MAV_COMPONENT[44] = "MAV_COMP_ID_USER20"
MAV_COMPONENT[45] = "MAV_COMP_ID_USER21"
MAV_COMPONENT[46] = "MAV_COMP_ID_USER22"
MAV_COMPONENT[47] = "MAV_COMP_ID_USER23"
MAV_COMPONENT[48] = "MAV_COMP_ID_USER24"
MAV_COMPONENT[49] = "MAV_COMP_ID_USER25"
MAV_COMPONENT[50] = "MAV_COMP_ID_USER26"
MAV_COMPONENT[51] = "MAV_COMP_ID_USER27"
MAV_COMPONENT[52] = "MAV_COMP_ID_USER28"
MAV_COMPONENT[53] = "MAV_COMP_ID_USER29"
MAV_COMPONENT[54] = "MAV_COMP_ID_USER30"
MAV_COMPONENT[55] = "MAV_COMP_ID_USER31"
MAV_COMPONENT[56] = "MAV_COMP_ID_USER32"
MAV_COMPONENT[57] = "MAV_COMP_ID_USER33"
MAV_COMPONENT[58] = "MAV_COMP_ID_USER34"
MAV_COMPONENT[59] = "MAV_COMP_ID_USER35"
MAV_COMPONENT[60] = "MAV_COMP_ID_USER36"
MAV_COMPONENT[61] = "MAV_COMP_ID_USER37"
MAV_COMPONENT[62] = "MAV_COMP_ID_USER38"
MAV_COMPONENT[63] = "MAV_COMP_ID_USER39"
MAV_COMPONENT[64] = "MAV_COMP_ID_USER40"
MAV_COMPONENT[65] = "MAV_COMP_ID_USER41"
MAV_COMPONENT[66] = "MAV_COMP_ID_USER42"
MAV_COMPONENT[67] = "MAV_COMP_ID_USER43"
MAV_COMPONENT[68] = "MAV_COMP_ID_TELEMETRY_RADIO"
MAV_COMPONENT[69] = "MAV_COMP_ID_USER45"
MAV_COMPONENT[70] = "MAV_COMP_ID_USER46"
MAV_COMPONENT[71] = "MAV_COMP_ID_USER47"
MAV_COMPONENT[72] = "MAV_COMP_ID_USER48"
MAV_COMPONENT[73] = "MAV_COMP_ID_USER49"
MAV_COMPONENT[74] = "MAV_COMP_ID_USER50"
MAV_COMPONENT[75] = "MAV_COMP_ID_USER51"
MAV_COMPONENT[76] = "MAV_COMP_ID_USER52"
MAV_COMPONENT[77] = "MAV_COMP_ID_USER53"
MAV_COMPONENT[78] = "MAV_COMP_ID_USER54"
MAV_COMPONENT[79] = "MAV_COMP_ID_USER55"
MAV_COMPONENT[80] = "MAV_COMP_ID_USER56"
MAV_COMPONENT[81] = "MAV_COMP_ID_USER57"
MAV_COMPONENT[82] = "MAV_COMP_ID_USER58"
MAV_COMPONENT[83] = "MAV_COMP_ID_USER59"
MAV_COMPONENT[84] = "MAV_COMP_ID_USER60"
MAV_COMPONENT[85] = "MAV_COMP_ID_USER61"
MAV_COMPONENT[86] = "MAV_COMP_ID_USER62"
MAV_COMPONENT[87] = "MAV_COMP_ID_USER63"
MAV_COMPONENT[88] = "MAV_COMP_ID_USER64"
MAV_COMPONENT[89] = "MAV_COMP_ID_USER65"
MAV_COMPONENT[90] = "MAV_COMP_ID_USER66"
MAV_COMPONENT[91] = "MAV_COMP_ID_USER67"
MAV_COMPONENT[92] = "MAV_COMP_ID_USER68"
MAV_COMPONENT[93] = "MAV_COMP_ID_USER69"
MAV_COMPONENT[94] = "MAV_COMP_ID_USER70"
MAV_COMPONENT[95] = "MAV_COMP_ID_USER71"
MAV_COMPONENT[96] = "MAV_COMP_ID_USER72"
MAV_COMPONENT[97] = "MAV_COMP_ID_USER73"
MAV_COMPONENT[98] = "MAV_COMP_ID_USER74"
MAV_COMPONENT[99] = "MAV_COMP_ID_USER75"
MAV_COMPONENT[100] = "MAV_COMP_ID_CAMERA"
MAV_COMPONENT[101] = "MAV_COMP_ID_CAMERA2"
MAV_COMPONENT[102] = "MAV_COMP_ID_CAMERA3"
MAV_COMPONENT[103] = "MAV_COMP_ID_CAMERA4"
MAV_COMPONENT[104] = "MAV_COMP_ID_CAMERA5"
MAV_COMPONENT[105] = "MAV_COMP_ID_CAMERA6"
MAV_COMPONENT[140] = "MAV_COMP_ID_SERVO1"
MAV_COMPONENT[141] = "MAV_COMP_ID_SERVO2"
MAV_COMPONENT[142] = "MAV_COMP_ID_SERVO3"
MAV_COMPONENT[143] = "MAV_COMP_ID_SERVO4"
MAV_COMPONENT[144] = "MAV_COMP_ID_SERVO5"
MAV_COMPONENT[145] = "MAV_COMP_ID_SERVO6"
MAV_COMPONENT[146] = "MAV_COMP_ID_SERVO7"
MAV_COMPONENT[147] = "MAV_COMP_ID_SERVO8"
MAV_COMPONENT[148] = "MAV_COMP_ID_SERVO9"
MAV_COMPONENT[149] = "MAV_COMP_ID_SERVO10"
MAV_COMPONENT[150] = "MAV_COMP_ID_SERVO11"
MAV_COMPONENT[151] = "MAV_COMP_ID_SERVO12"
MAV_COMPONENT[152] = "MAV_COMP_ID_SERVO13"
MAV_COMPONENT[153] = "MAV_COMP_ID_SERVO14"
MAV_COMPONENT[154] = "MAV_COMP_ID_GIMBAL"
MAV_COMPONENT[155] = "MAV_COMP_ID_LOG"
MAV_COMPONENT[156] = "MAV_COMP_ID_ADSB"
MAV_COMPONENT[157] = "MAV_COMP_ID_OSD"
MAV_COMPONENT[158] = "MAV_COMP_ID_PERIPHERAL"
MAV_COMPONENT[159] = "MAV_COMP_ID_QX1_GIMBAL"
MAV_COMPONENT[160] = "MAV_COMP_ID_FLARM"
MAV_COMPONENT[161] = "MAV_COMP_ID_PARACHUTE"
MAV_COMPONENT[171] = "MAV_COMP_ID_GIMBAL2"
MAV_COMPONENT[172] = "MAV_COMP_ID_GIMBAL3"
MAV_COMPONENT[173] = "MAV_COMP_ID_GIMBAL4"
MAV_COMPONENT[174] = "MAV_COMP_ID_GIMBAL5"
MAV_COMPONENT[175] = "MAV_COMP_ID_GIMBAL6"
MAV_COMPONENT[180] = "MAV_COMP_ID_BATTERY"
MAV_COMPONENT[181] = "MAV_COMP_ID_BATTERY2"
MAV_COMPONENT[189] = "MAV_COMP_ID_MAVCAN"
MAV_COMPONENT[190] = "MAV_COMP_ID_MISSIONPLANNER"
MAV_COMPONENT[191] = "MAV_COMP_ID_ONBOARD_COMPUTER"
MAV_COMPONENT[192] = "MAV_COMP_ID_ONBOARD_COMPUTER2"
MAV_COMPONENT[193] = "MAV_COMP_ID_ONBOARD_COMPUTER3"
MAV_COMPONENT[194] = "MAV_COMP_ID_ONBOARD_COMPUTER4"
MAV_COMPONENT[195] = "MAV_COMP_ID_PATHPLANNER"
MAV_COMPONENT[196] = "MAV_COMP_ID_OBSTACLE_AVOIDANCE"
MAV_COMPONENT[197] = "MAV_COMP_ID_VISUAL_INERTIAL_ODOMETRY"
MAV_COMPONENT[198] = "MAV_COMP_ID_PAIRING_MANAGER"
MAV_COMPONENT[200] = "MAV_COMP_ID_IMU"
MAV_COMPONENT[201] = "MAV_COMP_ID_IMU_2"
MAV_COMPONENT[202] = "MAV_COMP_ID_IMU_3"
MAV_COMPONENT[220] = "MAV_COMP_ID_GPS"
MAV_COMPONENT[221] = "MAV_COMP_ID_GPS2"
MAV_COMPONENT[236] = "MAV_COMP_ID_ODID_TXRX_1"
MAV_COMPONENT[237] = "MAV_COMP_ID_ODID_TXRX_2"
MAV_COMPONENT[238] = "MAV_COMP_ID_ODID_TXRX_3"
MAV_COMPONENT[240] = "MAV_COMP_ID_UDP_BRIDGE"
MAV_COMPONENT[241] = "MAV_COMP_ID_UART_BRIDGE"
MAV_COMPONENT[242] = "MAV_COMP_ID_TUNNEL_NODE"
MAV_COMPONENT[250] = "MAV_COMP_ID_SYSTEM_CONTROL"
MAV_COMPONENT[251] = "MAV_COMPONENT_ENUM_END"

